<a href="https://colab.research.google.com/github/lintabong/Dashboarding-and-Data-Visualization/blob/main/Matrix-Distance-From-LatLon/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install openpyxl
!pip install geopy
!pip install math
!pip install numpy

In [ ]:
import math
import openpyxl         as xcl
import numpy            as np
import geopy.distance   as geo
from google.colab       import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/00_YOUTUBE/01/'

workbook    = xcl.load_workbook(path + 'tabel.xlsx')
sheet       = workbook.active

print(workbook.sheetnames)

place           = {}
name, lat, lon  = '', 0, 0
values          = ['B', 'D', 'E']

for i in range(3, 11):
    arr = []
    for o, val in enumerate(values):
        arr.append(str(val) + str(i))

    name = sheet[arr[0]].value
    lat  = sheet[arr[1]].value
    log  = sheet[arr[2]].value

    place[name] = (lat, lon)

print(place)

['latlon']
{'Taman Balekambang Surakarta': (-7.55151296671099, 0), 'RSUD Moewardi': (-7.5562777724881, 0), 'Kebun Binatang Jurug': (-7.56104252570266, 0), 'Alun-Alun Kidul Surakarta': (-7.58044133474522, 0), 'De Tjolomadoe': (-7.53212728391324, 0), 'Grup 2 Kopassus': (-7.55748339043393, 0), 'Umbul Pengging': (-7.55101687361919, 0), 'Tugu Lilin': (-7.56480064794458, 0)}


In [ ]:
matrix_distance = np.zeros([len(place), len(place)])

print(matrix_distance)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
y = 0
for i, o in place.items():
    x = 0
    for city, coord in place.items():
        distance = geo.distance(place[i], coord).m
        matrix_distance[x, y] = int(distance)
        x += 1
    y += 1

print(matrix_distance)

[[   0.  526. 1053. 3199. 2143.  660.   54. 1469.]
 [ 526.    0.  526. 2672. 2670.  133.  581.  942.]
 [1053.  526.    0. 2145. 3197.  393. 1108.  415.]
 [3199. 2672. 2145.    0. 5343. 2539. 3254. 1729.]
 [2143. 2670. 3197. 5343.    0. 2804. 2089. 3613.]
 [ 660.  133.  393. 2539. 2804.    0.  715.  809.]
 [  54.  581. 1108. 3254. 2089.  715.    0. 1524.]
 [1469.  942.  415. 1729. 3613.  809. 1524.    0.]]


In [ ]:
export_wb   = xcl.Workbook()
sh_export   = export_wb.active

In [ ]:
a     = []
char  = 65
for i in range(char, char + len(place)):
    a.append(chr(i))
print(a)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']


In [ ]:
for i, o in enumerate(a):
    for p in range(1, 9):
        sh_export[str(o) + str(p)] = matrix_distance[i, p-1]

export_wb.save(path + 'export.xlsx')